import tt_lib.tensor
import ttnn._ttnn.types
from typing import List, overload

@overload
def reshape(tensor: tt_lib.tensor.Tensor, shape: ttnn._ttnn.types.Shape) -> tt_lib.tensor.Tensor: ...
@overload
def reshape(tensor: tt_lib.tensor.Tensor, shape: List[int[1]]) -> tt_lib.tensor.Tensor: ...
@overload
def reshape(tensor: tt_lib.tensor.Tensor, shape: List[int[2]]) -> tt_lib.tensor.Tensor: ...
@overload
def reshape(tensor: tt_lib.tensor.Tensor, shape: List[int[3]]) -> tt_lib.tensor.Tensor: ...
@overload
def reshape(tensor: tt_lib.tensor.Tensor, shape: List[int[4]]) -> tt_lib.tensor.Tensor: ...
def unsqueeze_to_4D(tensor: tt_lib.tensor.Tensor) -> tt_lib.tensor.Tensor: ...
