from typing import ClassVar, Dict, List

EPS_GS: float
EPS_WHB0: float

class Arch:
    __members__: ClassVar[dict] = ...  # read-only
    GRAYSKULL: ClassVar[Arch] = ...
    WORMHOLE_B0: ClassVar[Arch] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Device:
    def __init__(self, arg0: int) -> None: ...
    def arch(self) -> Arch: ...
    def compute_with_storage_grid_size(self) -> tt_xy_pair: ...
    def disable_and_clear_program_cache(self) -> None: ...
    def enable_program_cache(self) -> None: ...
    def id(self) -> int: ...
    def num_program_cache_entries(self) -> int: ...
    def sfpu_eps(self) -> float: ...
    def worker_core_from_logical_core(self, arg0: tt_xy_pair) -> tt_xy_pair: ...

def CloseDevice(arg0: Device) -> bool: ...
def CloseDevices(arg0: Dict[int, Device]) -> None: ...
def CreateDevice(arg0: int) -> Device: ...
def CreateDevices(arg0: List[int]) -> Dict[int, Device]: ...
def DeallocateBuffers(arg0: Device) -> None: ...
def DisableCompilationReports() -> None: ...
def DisableMemoryReports() -> None: ...
def DisablePersistentKernelCache() -> None: ...
def DumpDeviceMemoryState(arg0: Device) -> None: ...
def EnableCompilationReports() -> None: ...
def EnableMemoryReports() -> None: ...
def EnablePersistentKernelCache() -> None: ...
def GetDefaultDevice() -> Device: ...
def GetNumAvailableDevices() -> int: ...
def GetNumPCIeDevices() -> int: ...
def SetDefaultDevice(arg0: Device) -> None: ...
def SetLazyCommandQueueMode(arg0: bool) -> None: ...
def Synchronize(arg0: Device) -> None: ...
